### PR TITLE
travis: PHP 7.0 nightly added

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by cboden** [comment]
Any chance you could get TravisCI to build the extensions and run the test suite?

**Comment by TomasVotruba** [comment]
I'm not sure what do you mean. Could you elaborate?

**Comment by WyriHaximus** [comment]
The PHP extensions needed for the test fail during build time: https://travis-ci.org/reactphp/react/jobs/59153786#L493-L494

**Comment by TomasVotruba** [comment]
I see. It's probably due to development version of PHP 7. For this reason I've added to allowed failures.
When it's ready (stable or with working extensions), it could be moved out of this section.

**Pull request closed without merging**
