### PR TITLE
Improve support section

### PR DESCRIPTION
**Pull request by clue**
Builds on top of #409. The idea is to add a single "#support" section to this README and then add the same section to our website so we have a single place to link people to.

Refs #348

### CODE REVIEW

**Comment by jsor** [comment]
Why not keep it above the Tests section at the same place as the former Community section?

**Comment by clue** [comment]
> Why not keep it above the Tests section at the same place as the former Community section?

No preference here, either position works for me :+1:

**Comment by WyriHaximus** [comment]
I'm work @jsor on this, keeping above Tests looks better

**Comment by clue** [comment]
There you go, updated as per your suggestion! :+1: 

The "Tests" section is not currently part of the website anyway, so it will likely end up near the bottom of the website anyway (which I think is the right place for this) :+1:

**Pull request merged**
